apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- store1.yml
- store2.yml
- store3.yml
- store4.yml
- namespace.yml
- smm.yml
- dr.yml
- jaeger.yml

images:
- name: localhost/producer
  newName: quay.io/rhn_support_milang/kafka-demo/producer

namespace: producers
