apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dr.yml
- frontend.yml
- service.yml
- vs.yml
- namespace.yml
- smm.yml
- se.yml
- jaeger.yml

images:
- name: localhost/frontend
  newName: quay.io/rhn_support_milang/kafka-demo/frontend

namespace: kafka
