apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kitchen1.yml
- kitchen2.yml
- waiter1.yml
- waiter2.yml
- namespace.yml
- smm.yml
- dr.yml
- jaeger.yml

images:
- name: localhost/consumer
  newName: quay.io/rhn_support_milang/kafka-demo/consumer

namespace: consumers
